### ISSUE TITLE
pip install fairseq2 - doesn't work

### ISSUE THREAD

**Issue by saneqq** [facebookresearch/fairseq2#1]
```
pip install fairseq2
Collecting fairseq2
  Obtaining dependency information for fairseq2 from https://files.pythonhosted.org/packages/cd/27/46c14e28e8cb0aa602660ce64d4547a37f460d382e4fcf94f2a53d47e5b0/fairseq2-0.1.0-py3-none-any.whl.metadata
  Using cached fairseq2-0.1.0-py3-none-any.whl.metadata (1.2 kB)
INFO: pip is looking at multiple versions of fairseq2 to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement fairseq2n==0.1.0 (from fairseq2) (from versions: none)
ERROR: No matching distribution found for fairseq2n==0.1.0

```

**Comment by cbalioglu** [comment]
Do you mind sharing which operating system and Python version you are using?

**Comment by zouharvi** [comment]
I'm getting the same error - `fairseq2n` not found. This is strange because it's on PyPi: https://pypi.org/project/fairseq2n/.

**Comment by cbalioglu** [comment]
@zouharvi same question, do you mind sharing your environment details?

**Comment by rgryta** [comment]
From the looks of it, fairseq2n only has wheels for Linux available. Are you perhaps using Windows?

**Comment by zouharvi** [comment]
Ah, that's the catch. I was testing on MacOS. It works well on Linux.

**Comment by cbalioglu** [comment]
@rgryta we have couple places in our code base where we rely on fairseq2n. For instance we have a PyTorch native implementation of sentencepiece written in C++ and most of our models use that implementation for their tokenizers. Having said that, depending on users' feedback, I will check whether I can refactor it even further and make it an optional dependency.

**Comment by rgryta** [comment]
> @rgryta we have couple places in our code base where we rely on fairseq2n. For instance we have a PyTorch native [...] whether I can refactor it even further and make it an optional dependency.

Not complaining, by any means. You guys have been doing tremendously good work. I guess a temporary workaround for people without Linux would be to install a dummy fairseq2n module before installing fairseq2 wheel (from what I saw those are for any os) and then uninstall the former.

**Comment by tigerhawkvok** [comment]
Attempting to build from source also fails with a `tbb-devel` requirement failure:

```
 fairseq2  pip install torch -r fairseq2n/python/requirements-build.txt
Collecting torch
  Using cached torch-2.0.1-cp38-cp38-win_amd64.whl (172.4 MB)
Collecting cmake~=3.26
  Downloading cmake-3.27.2-py2.py3-none-win_amd64.whl (34.6 MB)
     |████████████████████████████████| 34.6 MB 6.8 MB/s
Collecting ninja~=1.11
  Downloading ninja-1.11.1-py2.py3-none-win_amd64.whl (313 kB)
     |████████████████████████████████| 313 kB ...
Requirement already satisfied: packaging~=23.1 in c:\users\pkahn\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages (from -r fairseq2n/python/requirements-build.txt (line 3)) (23.1)
Collecting pip~=23.2
  Downloading pip-23.2.1-py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB ...
Collecting setuptools~=67.8
  Using cached setuptools-67.8.0-py3-none-any.whl (1.1 MB)
ERROR: Could not find a version that satisfies the requirement tbb-devel==2021.8 (from versions: 2021.1.1, 2021.2.0, 2021.3.0, 2021.4.0, 2021.5.0, 2021.5.1, 2021.5.2, 2021.6.0, 2021.7.0, 2021.7.1, 2021.9.0, 2021.10.0)
ERROR: No matching distribution found for tbb-devel==2021.8
```


I've gotten through a few hurdles on Windows, but it'll take me a few days to really get back to it:

```pwsh
git clone --recurse-submodules https://github.com/facebookresearch/fairseq2.git
cd fairseq2
# Manually change dependency tbb-devel to tbb-devel==2021.9
pip install torch -r fairseq2n/python/requirements-build.txt
cd fairseq2n
# TODO sndfile see https://gist.github.com/sveinse/97411b95d36a6b8c430d4d381b620ecb
cmake -GNinja -B build
cmake --build build
cd python
pip install -e .
cd ../..
$env:FAIRSEQ2N_DEVEL=1 
pip install -e .
cd ..
git clone --recurse-submodules --depth 1 https://github.com/facebookresearch/seamless_communication.git
cd seamless_communication
pip install .
```

I'll bundle it up at some point when I've gotten it deployed.

**Comment by rgryta** [comment]
tbb-devel does not have windows wheel available in pip for that particular release: https://pypi.org/project/tbb-devel/2021.8.0/#files

Updating requirements to newer version could work, or building your own wheel for windows (repository has proper tags and 2021.8.0 is there).

**Comment by janvarev** [comment]
Same problem here - can't install fairseq2 on Win, Python 3.10, torch 2.0.1. Hope this will be solved soon.

**Comment by ramzzzay** [comment]
Same problem on `Darwin Antons-MacBook-Pro.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 arm64` `(MacBook Pro m1 pro; macOS 13.5)`

**Comment by electrotuto** [comment]
Hello,
Same problem for me on :

> 5.15.0-79-generic #86~20.04.2-Ubuntu 
> pip 20.0.2 python3.8

`ERROR: Could not find a version that satisfies the requirement fairseq2n==0.1.0 (from fairseq2) (from versions: none)
ERROR: No matching distribution found for fairseq2n==0.1.0 (from fairseq2)`

**Comment by changeling** [comment]
Same.
Apple Silicon, M1
Python 3.11

Following the Install from Source instructions:
`pip install .`
`ERROR: Could not find a version that satisfies the requirement fairseq2n==0.1.0 (from fairseq2) (from versions: none)`
`ERROR: No matching distribution found for fairseq2n==0.1.0`

**Comment by BwandoWando** [comment]
I am trying to install it into a Kaggle compute, the error I'm countering can be found below

- NAME="Ubuntu"
- VERSION="20.04.6 LTS (Focal Fossa)"
- ID=ubuntu
- ID_LIKE=debian
- PRETTY_NAME="Ubuntu 20.04.6 LTS"
- VERSION_ID="20.04"


![ScreenClip](https://github.com/facebookresearch/fairseq2/assets/11482721/ed8bc3fc-4e7d-4f2a-b6a6-785affb4a62b)

**Comment by changeling** [comment]
@cbalioglu Any thoughts?

**Comment by allwinj** [comment]
I have the same issue. Trying to build seamlessmt4

Collecting fairseq2
  Obtaining dependency information for fairseq2 from https://files.pythonhosted.org/packages/cd/27/46c14e28e8cb0aa602660ce64d4547a37f460d382e4fcf94f2a53d47e5b0/fairseq2-0.1.0-py3-none-any.whl.metadata
  Using cached fairseq2-0.1.0-py3-none-any.whl.metadata (1.2 kB)
INFO: pip is looking at multiple versions of fairseq2 to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement fairseq2n==0.1.0 (from fairseq2) (from versions: none)
ERROR: No matching distribution found for fairseq2n==0.1.0

**Comment by ramonmarrero** [comment]
Hi All, 
I was also facing this issue. Make sure you are using a Python version higher than 3.8.

**Comment by yokotoka** [comment]
Python 3.11.4
Apple M1

```
% CFLAGS="-stdlib=libc++" pip install -e ./
Obtaining file:///Users/yokotoka/Documents/p/unbabeler/seamless_communication/fairseq2
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
INFO: pip is looking at multiple versions of fairseq2 to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement fairseq2n==0.1.0 (from fairseq2) (from versions: none)
ERROR: No matching distribution found for fairseq2n==0.1.0
```

**Comment by IronBlood** [comment]
> I'm getting the same error - `fairseq2n` not found. This is strange because it's on PyPi: https://pypi.org/project/fairseq2n/.

I think the problem is that fairseq2n as a native CUDA library, is currently only built for Linux, as you can see from https://pypi.org/project/fairseq2n/#files and also from the GitHub workflow files. Does that mean it's not compatible Apple Silicon even if like I only want to install the python package to get LSP support?

**Comment by cbalioglu** [comment]
Hey folks, I am working on v0.1.1 right now that will fix some of the issues you have been experiencing. Two side notes though:

- We do not support Windows and have no plans to support it (mostly due to lack of bandwidth and lack of experience in Windows development). I will make sure that I have some installation instructions for WSL2 though. Considering that WSL2 now has pretty stable CUDA support, I hope that this will be a sufficient middle ground for Windows users.
- For Mac users, I am also working on pre-built ARM64 binaries. We use GitHub Actions for our CI and unfortunately GHA still has no support for M1/M2 runners, so this requires some manual work on my end.

I expect to finish v0.1.1 by tomorrow (08/29), and will keep you posted!

**Comment by martincpt** [comment]
Same issues, watching this thread.

**Comment by MoidAmer-srijan** [comment]
I am also having same issue. 
Python 3.10
MacOS 13 on M1 chipset.

**Comment by chipcode-nl** [comment]
For other Mac users, I created two script to build fairseq2 on the Mac. Tested on a M2 chipset.
https://github.com/chipcode-nl/mac-fairseq2

**Comment by Sharrnah** [comment]
WSL isn't really an option for me unfortunately. So i still hope Windows will be supported in the future.

**Comment by Woofdogcat** [comment]
Unfortunately fairseq2 is not installing in my windows11, wsl ubuntu 20.04, python 3.9.10 environment. I hope that fairseq2 can be used in the Windows environment as well as others.

**Comment by tungp55** [comment]
For someone use Linux, I just download it by upgrade pip:
```
pip install --upgrade pip
pip install fairseq2
```
That work for me

**Comment by mahditalebi** [comment]
I'm using a Mac and still have the following error:

```
ERROR: Could not find a version that satisfies the requirement fairseq2n==0.1.0 (from fairseq2) (from versions: none)
ERROR: No matching distribution found for fairseq2n==0.1.0
```

Somebody please help.

**Comment by huangwei2913** [comment]
does anyone successfully compile fairseq2n from source？ Please detail the compiling steps, thanks in advance

**Comment by martincpt** [comment]
> https://github.com/chipcode-nl/mac-fairseq2

@huangwei2913 this dude made a repo, I just followed the steps in the build bash file and it worked. Thanks for @chipcode-nl !

**Comment by huangwei2913** [comment]
@martincpt I appreciate your help.  is it possible to offer all the source codes of the faireseq2 with the third party? In China, the git speed is rather terrible

**Comment by huangwei2913** [comment]
@martincpt By the way , my email address is huangwei2913@gmail.com, thanks a lot

**Comment by chongthon** [comment]
@chipcode-nl @martincpt @huangwei2913 When I followed these steps, I encountered an issue and couldn't cmake.
```shell
CMake Error at /Users/chong/miniconda3/envs/seamless_m4t/lib/python3.9/site-packages/cmake/data/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Torch (missing: TORCH_LIBRARY TORCH_CPU_LIBRARY C10_LIBRARY
  TORCH_INCLUDE_DIR TORCH_API_INCLUDE_DIR) (Required is at least version
  "1.12")
Call Stack (most recent call first):
  /Users/chong/miniconda3/envs/seamless_m4t/lib/python3.9/site-packages/cmake/data/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindTorch.cmake:114 (find_package_handle_standard_args)
  CMakeLists.txt:167 (find_package)
```
https://github.com/chipcode-nl/mac-fairseq2/issues/1#issue-1884649037

**Comment by cocktailpeanut** [comment]
@cbalioglu any updates on mac support sir? literally keeping this tab open and refreshing multiple times a day since i started following this thread :)

**Comment by huangwei2913** [comment]
@cocktailpeanut I think you should build faireseq2 from source code and use Linux rather than mac.  I solved the problem

**Comment by cocktailpeanut** [comment]
I'm trying to build this for end users, not for a server purpose, so getting it to work natively on mac is important. Also I know I can build myself but would prefer that this comes prebuilt, especially since @cbalioglu said it's coming.

**Comment by cbalioglu** [comment]
Hey everyone, yesterday I released v0.1.1 that tries to address some of the issues you have been experiencing. I also significantly revised the installation instructions in README. We also have a pre-built package for Apple-silicon computers now. Please try the installation in a fresh environment by following the instructions in README and let me know how it goes. Thank you!

**Comment by chongthon** [comment]
@cbalioglu 
```pytest```
there is error:
```bash
Reason: tried: '/usr/local/lib/libfairseq2n.0.dylib' (no such file), '/usr/lib/libfairseq2n.0.dylib' (no such file, not in dyld cache)
```
my system Mac OS ventura 13.4.1
Intel-silicon

**Comment by cbalioglu** [comment]
@chongthon Do you mind configuring CMake build with `cmake -GNinja -DFAIRSEQ2N_INSTALL_STANDALONE=ON -B build`?

**Comment by cbalioglu** [comment]
Closing this issue since it diverged from the original question which should be resolved now with v0.1.1. If anyone has still trouble installing the project, please feel free to open a new issue.

**Comment by aiexpert-79** [comment]
windows 10 enterprise, python 3.10.5, the fairseq2 is not installed in my PC. If I install this package on Ubuntu, is it possible?

**Comment by M2LabOrg** [comment]
@cbalioglu thanks for creating v0.1.1. I have been trying to install it on a Macbook (M1 Pro) in a fresh environment, but I still get an error. Do you have any suggestions?

```
$ pip install fairseq2==0.1.1
Collecting fairseq2==0.1.1
  Using cached fairseq2-0.1.1-py3-none-any.whl.metadata (1.2 kB)
INFO: pip is looking at multiple versions of fairseq2 to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement fairseq2n==0.1.1 (from fairseq2) (from versions: none)
ERROR: No matching distribution found for fairseq2n==0.1.1
```


And:


```
$ pip install fairseq2
Collecting fairseq2
  Using cached fairseq2-0.2.0-py3-none-any.whl.metadata (1.2 kB)
INFO: pip is looking at multiple versions of fairseq2 to determine which version is compatible with other requirements. This could take a while.
  Using cached fairseq2-0.1.1-py3-none-any.whl.metadata (1.2 kB)
  Using cached fairseq2-0.1.0-py3-none-any.whl.metadata (1.2 kB)
ERROR: Cannot install fairseq2==0.1.0, fairseq2==0.1.1 and fairseq2==0.2.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    fairseq2 0.2.0 depends on fairseq2n==0.2.0
    fairseq2 0.1.1 depends on fairseq2n==0.1.1
    fairseq2 0.1.0 depends on fairseq2n==0.1.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by silentlit** [comment]
I find that, it might because python recognize macos version error.
Activating your python env, import platform, and run platform.platform(). If the print is not equal to your macos version, this error would happen.
Reboot and use the Terminal to create python env might fit this problem.
It work for me.

**Comment by M2LabOrg** [comment]
Thank you @silentlit for your assistance.
A friend recommended that I try miniforge instead of virtualenvwrapper. This suggestion worked well, and I successfully installed fairseq2.

**Comment by manforowicz** [comment]
I couldn't install on Python 3.12:
```
$ pip install fairseq2
Collecting fairseq2
  Using cached fairseq2-0.2.1-py3-none-any.whl.metadata (1.2 kB)
INFO: pip is looking at multiple versions of fairseq2 to determine which version is compatible with other requirements. This could take a while.
  Using cached fairseq2-0.2.0-py3-none-any.whl.metadata (1.2 kB)
  Using cached fairseq2-0.1.1-py3-none-any.whl.metadata (1.2 kB)
  Using cached fairseq2-0.1.0-py3-none-any.whl.metadata (1.2 kB)
ERROR: Cannot install fairseq2==0.1.0, fairseq2==0.1.1, fairseq2==0.2.0 and fairseq2==0.2.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    fairseq2 0.2.1 depends on fairseq2n==0.2.1
    fairseq2 0.2.0 depends on fairseq2n==0.2.0
    fairseq2 0.1.1 depends on fairseq2n==0.1.1
    fairseq2 0.1.0 depends on fairseq2n==0.1.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

But installation worked flawlessly when I changed to Python 3.11.

**Comment by theoparis** [comment]
I got a similar to error to @manforowicz on a M2 Macbook running Asahi Linux (aarch64 linux) with python 3.13.

**Comment by IanMcGarryWWU** [comment]
I got a similar error on Windows - so I used WSL to boot up Linux then to install I had to use this command

pip install fairseq2 --index-url https://fair.pkg.atmeta.com/fairseq2/whl/rc/pt2.5.1/cpu/

I got the url from the pyproject.toml in SONAR project
